### ISSUE TITLE
Option to format specific cells

### ISSUE THREAD

**Issue by vikasrawal** [turbanisch/tabularray#1]
This is very useful for producing tabularray tables directly from R. Is it possible to extend this to cover some of the other features of tabularray as well. In particular, I was thinking if you could allow \SetCell formatting to be applied to arbitrary cells.

Thank you for creating this package.

**Comment by turbanisch** [comment]
While the current implementation does not encourage modifying specific cells in the table body, you can modify them using what's called the New Interface (see *2.4.1 Cells and Spancells in New Interfaces* in the [tabularray documentation](https://ftp.rrze.uni-erlangen.de/ctan/macros/latex/contrib/tabularray/tabularray.pdf)). 

For example, the following code allows you to adjust the cell span: 

```r
library(tidyverse)
library(tabularray)

df <- data.frame(
  name = c("Abc", "Def"),
  share = c(0.3, 0.53)
)

df |>
  tblr() |>
  set_interface(
    "cell{2}{1}" = c("c=2", "c")
  )
```

Output: 

```latex
\begin{center}
    \begin{booktabs}{
        colspec = {lr},
        cell{2}{1} = {c=2}{c}
        }
        \toprule
        name & share \\ 
        \midrule
        Abc  & 0.30  \\ 
        Def  & 0.53  \\ 
        \bottomrule
    \end{booktabs}
\end{center}
```

Renders to

<img width="156" alt="image" src="https://github.com/user-attachments/assets/b8019b38-bb5a-4c36-9986-a64ecbb22b94">
