### ISSUE TITLE
siunix with tabularray

### ISSUE THREAD

**Issue by vikasrawal** [turbanisch/tabularray#2]
Another desirable feature would be to allow use of siunitx, which tabularray is compatible with. As far as I know, neither gt nor kable/kableextra allow the use of siunitx.

This would be very useful.

Thanks very much.

**Comment by turbanisch** [comment]
I agree that some sort of convenience function would be nice to have but the functionality to use siunitx is already implemented through the New Interface (see *2.4.1 Cells and Spancells in New Interfaces* in the [tabularray documentation](https://ftp.rrze.uni-erlangen.de/ctan/macros/latex/contrib/tabularray/tabularray.pdf)): 

This example comes from Chapter 5.9 *Library siunitx* of the documentation: 

```r
library(tidyverse)
library(tabularray)

df <- tribble(
  ~Left, ~Right,
  "111", "111",
  "2.1", "2.2",
  "33.11", "33.22"
)

df |> 
  tblr() |> 
  set_alignment(everything() ~ "Q[si={table-format=3.2},c]") |>
  set_interface("row{1}" = "guard")
```

LaTeX markup: 

```latex
\documentclass{article}

\usepackage{tabularray}
\UseTblrLibrary{booktabs}
\UseTblrLibrary{siunitx}


\begin{document}

\begin{center}
    \begin{booktabs}{
        colspec = {Q[si={table-format=3.2},c]Q[si={table-format=3.2},c]},
        row{1} = {guard}
        }
        \toprule
        Left  & Right \\ 
        \midrule
        111   & 111   \\ 
        2.1   & 2.2   \\ 
        33.11 & 33.22 \\ 
        \bottomrule
    \end{booktabs}
\end{center}

\end{document}
```

Renders to:

<img width="162" alt="image" src="https://github.com/user-attachments/assets/2c8b3a4b-9ac6-4012-845f-1e8cb14c7987">
